# Generated by Django 5.2 on 2025-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес электронной почты (Login)",
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Ф. И. О."
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="Здесь пока ничего нет.",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["owner", "email", "initials"],
            },
        ),
    ]
