# Generated by Django 5.2 on 2025-04-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sending_messages",
            "0005_alter_mailing_options_remove_mailing_recipient_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["mailing", "create_at", "status", "server_response"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="malling",
            new_name="mailing",
        ),
    ]
