# Generated by Django 5.2 on 2025-05-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0008_alter_mailingrecipient_owner_alter_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("SUCCESSFULLY", "Успешно"), ("NOT_SUCCESSFUL", "Не успешно")],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
