# Generated by Django 5.2 on 2025-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0009_alter_mailingattempt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("SUCCESSFULLY", "Успешно"), ("NOT SUCCESSFUL", "Не успешно")],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
