# Generated by Django 5.2 on 2025-05-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0012_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Завершена"),
                    ("CREATED", "Создана"),
                    ("LAUNCHED", "Запущена"),
                ],
                default="Создана",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
