# Generated by Django 5.2 on 2025-05-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0013_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": [
                    "owner",
                    "first_sending",
                    "end_sending",
                    "status",
                    "message",
                ],
                "permissions": [
                    ("can_block_mailing", "Заблокировать/разблокировать рассылку")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["owner", "email", "initials"],
                "permissions": [
                    (
                        "can_block_recipient",
                        "Заблокировать/разблокировать получателя рассылки",
                    )
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["owner", "message_subject"],
                "permissions": [
                    ("can_block_message", "Заблокировать/разблокировать сообщение")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
