# Generated by Django 5.2 on 2025-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sending_messages",
            "0014_alter_mailing_options_alter_mailingrecipient_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="mailingrecipient",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Действующий"),
        ),
    ]
